export const aboutImageText = [
  {
    id: 1,
    text: "development",
    color: "black",
    fontSize: "3rem",
    orientation: "horizontal-tb",
    top: "6rem",
    left: "9rem",
  },
  {
    id: 2,
    text: "typography",
    color: "black",
    fontSize: "1.5rem",
    orientation: "horizontal-tb",
    top: "9rem",
    left: "10rem",
  },
  {
    id: 3,
    text: "mobility",
    color: "black",
    fontSize: "1rem",
    orientation: "horizontal-tb",
    top: "6rem",
    left: "11rem",
  },
  {
    id: 4,
    text: "project",
    color: "black",
    fontSize: "2rem",
    orientation: "horizontal-tb",
    top: "13rem",
    left: "9rem",
  },
  {
    id: 5,
    text: "designer",
    color: "black",
    fontSize: "2rem",
    orientation: "horizontal-tb",
    top: "9rem",
    left: "23rem",
  },
  {
    id: 6,
    text: "homepage",
    color: "black",
    fontSize: "1.5rem",
    orientation: "horizontal-tb",
    top: "3rem",
    left: "16rem",
  },
  {
    id: 7,
    text: "user",
    color: "gray",
    fontSize: "2rem",
    orientation: "horizontal-tb",
    top: "1rem",
    left: "17rem",
  },
  {
    id: 8,
    text: "responsive",
    color: "orange",
    fontSize: "1.5rem",
    orientation: "horizontal-tb",
    top: "13rem",
    left: "21rem",
  },
  {
    id: 9,
    text: "website",
    color: "orange",
    fontSize: "3.5rem",
    orientation: "horizontal-tb",
    top: "2.5rem",
    left: "4rem",
  },
  {
    id: 10,
    text: "flash",
    color: "gray",
    fontSize: "1rem",
    orientation: "horizontal-tb",
    top: "12.5rem",
    left: "10rem",
  },
  {
    id: 11,
    text: "professional",
    color: "gray",
    fontSize: "2rem",
    orientation: "horizontal-tb",
    top: "11rem",
    left: "21rem",
  },
  {
    id: 12,
    text: "html",
    color: "black",
    fontSize: "1.5rem",
    orientation: "horizontal-tb",
    top: "11rem",
    left: "13rem",
  },
  {
    id: 13,
    text: "content",
    color: "orange",
    fontSize: "1rem",
    orientation: "horizontal-tb",
    top: "11rem",
    left: "9rem",
  },
  {
    id: 14,
    text: "business",
    color: "orange",
    fontSize: "3rem",
    orientation: "horizontal-tb",
    top: "4rem",
    left: "18rem",
  },
  {
    id: 15,
    text: "css",
    color: "gray",
    fontSize: "2rem",
    orientation: "horizontal-tb",
    top: "6rem",
    left: "3rem",
  },
  {
    id: 16,
    text: "concept",
    color: "orange",
    fontSize: "2rem",
    orientation: "horizontal-tb",
    top: "1rem",
    left: "4rem",
  },
  {
    id: 17,
    text: "server",
    color: "black",
    fontSize: "1rem",
    orientation: "vertical-rl",
    top: "2rem",
    left: "3rem",
  },
  {
    id: 18,
    text: "industry",
    color: "black",
    fontSize: "1rem",
    orientation: "vertical-rl",
    top: "9rem",
    left: "4.5rem",
  },
  {
    id: 19,
    text: "interface",
    color: "orange",
    fontSize: "2rem",
    orientation: "vertical-rl",
    top: "7rem",
    left: "6rem",
  },
  {
    id: 20,
    text: "graphycs",
    color: "orange",
    fontSize: 1,
    orientation: "vertical-rl",
    top: 1,
    left: 1,
  },
  {
    id: 21,
    text: "internet",
    color: "orange",
    fontSize: "2rem",
    orientation: "vertical-rl",
    top: "9.5rem",
    left: "19rem",
  },
  {
    id: 22,
    text: "style",
    color: "black",
    fontSize: "1rem",
    orientation: "vertical-rl",
    top: "5rem",
    left: "17rem",
  },
  {
    id: 22,
    text: "evolution",
    color: "black",
    fontSize: "1rem",
    orientation: "vertical-rl",
    top: "11rem",
    left: "16rem",
  },
]
